SrvAddr: "0.0.0.0:50010"
EnabledSayer: "xunfei"
AzureSayer:
  SpeechKey: "your-key"
  SpeechRegion: "eastus"
  FormatMicrosoft: "audio-16khz-32kbitrate-mono-mp3"
  FormatMimeSubtype: "mp3"
  Roles:
    "default": '<speak version="1.0" xml:lang="zh-CN"><voice name="zh-CN-XiaoxiaoNeural">{{.}}</voice></speak>'
XunfeiSayer:
  ApiKey: "your-key"
  ApiSecret: "your-Secret"
  AppId: "you-appId"
